<?php return array (
  'Martin\\Forms\\Plugin' => 'plugins\\martin\\forms\\Plugin.php',
  'Offline\\Responsiveimages\\Plugin' => 'plugins\\offline\\responsiveimages\\Plugin.php',
  'Pandaprofit\\Projects\\Plugin' => 'plugins\\pandaprofit\\projects\\Plugin.php',
  'Rainlab\\Builder\\Plugin' => 'plugins\\rainlab\\builder\\Plugin.php',
  'Rainlab\\Deploy\\Plugin' => 'plugins\\rainlab\\deploy\\Plugin.php',
  'Rainlab\\Pages\\Plugin' => 'plugins\\rainlab\\pages\\Plugin.php',
  'OFFLINE\\ResponsiveImages\\Classes\\ResponsiveImagesMiddleware' => 'plugins\\offline\\responsiveimages\\classes\\ResponsiveImagesMiddleware.php',
  'RainLab\\Pages\\Classes\\Controller' => 'plugins\\rainlab\\pages\\classes\\Controller.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins\\rainlab\\pages\\classes\\Router.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins\\rainlab\\pages\\classes\\PageList.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins\\rainlab\\pages\\classes\\Page.php',
  'RainLab\\Pages\\Components\\StaticPage' => 'plugins\\rainlab\\pages\\components\\StaticPage.php',
  'RainLab\\Pages\\Classes\\Snippet' => 'plugins\\rainlab\\pages\\classes\\Snippet.php',
  'RainLab\\Pages\\Classes\\SnippetManager' => 'plugins\\rainlab\\pages\\classes\\SnippetManager.php',
  'Martin\\Forms\\Classes\\ReCaptcha' => 'plugins\\martin\\forms\\classes\\ReCaptcha.php',
  'Martin\\Forms\\Classes\\SharedProperties' => 'plugins\\martin\\forms\\classes\\SharedProperties.php',
  'Martin\\Forms\\Classes\\MagicForm' => 'plugins\\martin\\forms\\classes\\MagicForm.php',
  'Martin\\Forms\\Components\\EmptyForm' => 'plugins\\martin\\forms\\components\\EmptyForm.php',
  'Martin\\Forms\\Classes\\BackendHelpers' => 'plugins\\martin\\forms\\classes\\BackendHelpers.php',
  'Pandaprofit\\Projects\\Components\\FilterProjects' => 'plugins\\pandaprofit\\projects\\components\\FilterProjects.php',
  'Pandaprofit\\Projects\\Models\\Project' => 'plugins\\pandaprofit\\projects\\models\\Project.php',
);